ARG BASE_IMAGE="python:3.13-slim-bookworm"
# Use the official lightweight Python base image
FROM ${BASE_IMAGE} AS builder

# Set the working directory

WORKDIR /install


# Install gcc and build python requirements && remove all cached and uneeded files/packages
COPY requirements.txt /
RUN <<EOF
apt-get update
apt-get install --yes --no-install-recommends gcc g++ libffi-dev
# Install Python packages
pip install --no-cache-dir --prefix=/install -r /requirements.txt
apt-get purge --yes gcc g++ libff1-dev
apt-get autoremove --yes
rm -rf /var/lib/apt/lists/* /requirements.txt
EOF

# Final stage
FROM ${BASE_IMAGE}
ARG USER_NAME="predbat"
ARG USER_GROUP="predbat"
ARG UID="9005"
ARG GID="9005"
ARG PREDBAT_VERSION
ARG BASE_IMAGE
ARG BUILD_DATE
# Set the working directory
WORKDIR /config

RUN addgroup -gid ${GID} ${USER_GROUP} \
    && adduser -uid ${UID} -gid ${GID} ${USER_NAME} \
    && chown -R ${USER_NAME} /config

USER root

# Copy only the necessary files from the builder stage
# Copy Python packages from the builder stage
COPY --from=builder /install /usr/local/

# Copy required files including requirements file and install build dependencies
ADD --chown=${USER_NAME} https://github.com/springfall2008/batpred.git#$PREDBAT_VERSION:apps/predbat/ https://github.com/springfall2008/batpred.git#$PREDBAT_VERSION:apps/predbat/config/ rootfs/alpine/* /addon/
RUN chmod +x /addon/run.standalone.sh
USER root
# Define build arguments and labels

LABEL \
    io.hass.type="addon" \
    addon.version="1.4.1" \
    maintainer="nipar4 (https://github.com/nipar4/predbat_addon)" \
    org.opencontainers.image.vendor="Springfall2008" \
    org.opencontainers.image.authors="springfall2008, nipar4" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.url="https://github.com/springfall2008, https://github.com/nipar4/predbat_addon" \
    org.opencontainers.image.source="https://github.com/nipar4/predbat_addon" \
    org.opencontainers.image.documentation="https://github.com/springfall2008/predbat_addon/blob/main/predbat/DOCS.md" \
    org.opencontainers.image.created=${BUILD_DATE} \
    org.opencontainers.image.title="Predbat Addon Docker version" \
    org.opencontainers.image.base.digest=${BASE_IMAGE} \
    org.opencontainers.image.version=${PREDBAT_VERSION}

# Set the entrypoint to the startup script
ENTRYPOINT ["sh", "/addon/run.standalone.sh"]
