# Use the official lightweight Python base image
FROM python:3.11-slim-bookworm AS builder

# Set the working directory

WORKDIR /install


# Install gcc and build python requirements && remove all cached and uneeded files/packages
COPY requirements.txt /
RUN <<EOF
apt-get update
apt-get install --yes --no-install-recommends gcc g++ libffi-dev
# Install Python packages
pip install --no-cache-dir --prefix=/install -r /requirements.txt
apt-get purge --yes gcc g++ libff1-dev
apt-get autoremove --yes
rm -rf /var/lib/apt/lists/* /requirements.txt
EOF

# Final stage
FROM python:3.11-slim-bookworm
ARG USER_NAME="predbat"
ARG USER_GROUP="predbat"
ARG UID="9005"
ARG GID="9005"
ARG PREDBAT_VERSION="v8.11.0"
# Set the working directory
WORKDIR /config

RUN addgroup -gid ${GID} ${USER_GROUP} \
    && adduser -uid ${UID} -gid ${GID} ${USER_NAME} \
    && chown -R ${USER_NAME} /config

# Copy only the necessary files from the builder stage
# Copy Python packages from the builder stage
COPY --from=builder /install /usr/local/

USER root
# Copy required files including requirements file and install build dependencies
ADD https://github.com/springfall2008/batpred.git#$PREDBAT_VERSION:apps/predbat/ https://github.com/springfall2008/batpred.git#$PREDBAT_VERSION:apps/predbat/config/ rootfs/alpine/* /addon/

USER root
# Define build arguments and labels
ARG BUILD_ARCH
ARG BUILD_DATE
ARG BUILD_DESCRIPTION
ARG BUILD_NAME
ARG BUILD_REF
ARG BUILD_REPOSITORY
ARG BUILD_VERSION
LABEL \
    io.hass.name="${BUILD_NAME}" \
    io.hass.description="${BUILD_DESCRIPTION}" \
    io.hass.arch="${BUILD_ARCH}" \
    io.hass.type="addon" \
    io.hass.version=${BUILD_VERSION} \
    maintainer="springfall2008 (https://github.com/springfall2008)" \
    org.opencontainers.image.title="${BUILD_NAME}" \
    org.opencontainers.image.description="${BUILD_DESCRIPTION}" \
    org.opencontainers.image.vendor="Springfall2008" \
    org.opencontainers.image.authors="springfall2008 (https://github.com/springfall2008)" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.url="https://github.com/springfall2008" \
    org.opencontainers.image.source="https://github.com/${BUILD_REPOSITORY}" \
    org.opencontainers.image.documentation="https://github.com/${BUILD_REPOSITORY}/blob/main/README.md" \
    org.opencontainers.image.created=${BUILD_DATE} \
    org.opencontainers.image.revision=${BUILD_REF} \
    org.opencontainers.image.version=${BUILD_VERSION}

# Set the entrypoint to the startup script
ENTRYPOINT ["sh", "/addon/run.standalone.sh"]
